DROP TABLE IF EXISTS USER;  
CREATE TABLE USER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  username VARCHAR(250) NOT NULL,
  password VARCHAR(250) NOT NULL,
  name VARCHAR(250) NOT NULL,
  surname1 VARCHAR(250) NOT NULL,
  surname2 VARCHAR(250) NOT NULL
);


DROP TABLE IF EXISTS product;
CREATE TABLE PRODUCT (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  price double NOT NULL
);

DROP TABLE IF EXISTS panier;
CREATE TABLE PANIER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  idprod INT not null,
  name VARCHAR(250) NOT NULL,
  price double NOT NULL
);